name: fluff
description: "Flutter Leveraging User Functions from Friends."
version: 0.0.1
homepage: https://github.com/3vmartinet/fluff

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  android_id: ^0.4.0
  animated_text_kit: ^4.2.3
  audioplayers: ^6.5.1
  connectivity_plus: ^6.1.3
  device_info_plus: ^10.1.0
  flutter_adaptive_scaffold: ^0.2.2
  flutter_timezone: ^4.1.0
  http: ^1.4.0
  intl: ^0.20.2
  logging: ^1.3.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  system_info_plus: ^0.0.6
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  volume_watcher_plus: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

